version: "3.9"

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-server
    privileged: true
    networks:
      - skynet
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  skynet:
    driver: bridge

volumes:
  jenkins_home:
